name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    strategy:
      matrix:
        include:
          - artifact: pdfium-win-x64
            target_os: win
            target_cpu: x64
            cfg: Release
            v8: disabled
            runner: windows-2019

    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
      - name: Set environment variables
        run: |
          cat >>$GITHUB_ENV <<END
          PDFium_V8=${{ matrix.v8 }}
          PDFium_CONFIGURATION=${{ matrix.cfg }}
          PDFium_TARGET_CPU=${{ matrix.target_cpu }}
          PDFium_TARGET_OS=${{ matrix.target_os }}
          PDFium_BRANCH=chromium/4696
          PDFium_VERSION=98.0.4696.0
          END
          steps/00-environment.sh
        shell: bash
      - name: Install (1/2)
        run: steps/01-install.sh
        shell: bash
      - name: Checkout PDFium
        run: steps/02-checkout.sh
        shell: bash
      - name: Apply patches
        run: steps/03-patch.sh
        shell: bash
      - name: Install (2/2)
        run: steps/04-install-extras.sh
        shell: bash
      - name: Configure build
        run: steps/05-configure.sh
        shell: bash
      - name: Build
        run: steps/06-build.sh
        shell: bash
      - name: Pack
        run: steps/07-pack.sh
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact }}
          path: staging/
